### ISSUE TITLE
How can I used DRAMSIM2?

### ISSUE THREAD

**Issue by Zhouwk7** [ucb-bar/testchipip#105]
In chipyard/sims/verilator/ file, I used follow command for simulation in order to test DRAM latency. 
`./simulator-chipyard-RoCCDMAStrideRocketConfig +verbose ./tests/DMAStrideTest/main.riscv 2>output/RoCCDMAStride
`
But the memory access latency is similar to SIMAXIMEM , the chapyard version without DRAMSIM2, so how can I used DRAMSIM2 to simulate DRAM? Is the command I used error? @asb @sbeamer @jwright6323 @zhemao @hcook

**Comment by colinschmidt** [comment]
If you use the makefile in chipyard/sims/verilator it will, by default, use dramsim:
https://github.com/ucb-bar/chipyard/blob/19152d3b73f1c2255ce378501f6c01f9363b75e9/variables.mk#L142
