### ISSUE TITLE
verilator-harness.cc broken due to (my) HTIF/FESVR API changes

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/testchipip#12]
My changes to HTIF killed verilator-harness.cc (in addition to SimSerial.cc, but it looks like @zhemao already took care of that) and that's percolated into project-template: https://github.com/ucb-bar/project-template/issues/25.

Basically, verilator-harness.cc just needs to be modified to pass argc/argv to tsi_t. However, that could benefit from a refactor to be more like emulator.cc and get all the command line arguments out in the open.

If I have time, I'll try and take a look.

**Comment by colinschmidt** [comment]
I think this was fixed with f8d7bed3e51b4ef5cd572a7cd4b4ca346fea2896
