### ISSUE TITLE
Failed to generate emulator with errors

### ISSUE THREAD

**Issue by cokeco** [ucb-bar/testchipip#13]
Hi, 
I clone the project-template project and desire to run it.
However, there are errors at build emulator stage.

[error] /RocketPlatform/testchipip/src/main/scala/Generator.scala:16: type mismatch;
[error]  found   : freechips.rocketchip.util.ParsedInputNames
[error]  required: Seq[String]
[error]   lazy val config = getConfig(names)
[error]                               ^
[error] /RocketPlatform/testchipip/src/main/scala/Generator.scala:18: value root is not a member of object freechips.rocketchip.config.Parameters
[error]   lazy val params = Parameters.root(world)
[error]                                ^
 [error] two errors found

It seems Generator.scala( in src/main/scala) needs to revise.
I am not sure that does it cause by using the latest rocket-chip version?

**Comment by colinschmidt** [comment]
Closed by #14
