### ISSUE TITLE
Incorrect type name in SimDram.cc

### ISSUE THREAD

**Issue by HakamAtassi** [ucb-bar/testchipip#207]
I believe lines 64 through 66 in src/main/testchip/csrc/SimDRAM.cc

should be modified as follows 

![image](https://github.com/ucb-bar/testchipip/assets/83780720/6d871e50-48f3-43f4-bb01-e3f82e33b703)

as endianness_t is not defined anywhere.

This fixes an issue when building with building esp-tools and subsequently hwacha in chipyard.

**Comment by HakamAtassi** [comment]
The required type seems to somehow depend on whether esp-tools or riscv-tools is being build.

**Comment by jerryz123** [comment]
This repository is no longer compatible with esp-tools
